# Generated by Django 6.0.4 on 2026-04-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_card_options_alter_card_expire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expire',
            field=models.DateField(default=False),
        ),
    ]
